#!/usr/bin/env python3
"""Deterministic factory-memory ingest route for AUTO-003.

The first version intentionally avoids LLM summarisation. It stores the source
chat or issue evidence and creates reviewable stubs for summary, decision,
lesson learned, and skill-update recommendation records.
"""
from __future__ import annotations

import argparse
import json
import re
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path

ALLOWED_INPUT_SUFFIXES = {".md", ".markdown", ".txt"}
MEMORY_DIRS = (
    "factory-memory/chats/inbox",
    "factory-memory/chats/processed",
    "factory-memory/chats/summaries",
    "factory-memory/decisions",
    "factory-memory/lessons-learned",
    "factory-memory/instructions",
    "factory-memory/skills",
    "factory-memory/agents",
    "factory-memory/plugins",
    "factory-memory/deployments",
    "factory-memory/registers",
)


@dataclass(frozen=True)
class IngestSource:
    source_type: str
    source_id: str
    title: str
    content: str
    original_path: str | None = None


def utc_stamp() -> str:
    return datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%SZ")


def slugify(value: str, fallback: str = "factory-memory-ingest") -> str:
    slug = re.sub(r"[^a-zA-Z0-9]+", "-", value.strip().lower()).strip("-")
    return slug[:80] or fallback


def ensure_within_root(root: Path, candidate: Path) -> Path:
    resolved_root = root.resolve()
    resolved_candidate = candidate.resolve()
    try:
        resolved_candidate.relative_to(resolved_root)
    except ValueError as exc:
        raise SystemExit(f"Input path is outside repository root: {candidate}") from exc
    return resolved_candidate


def ensure_memory_dirs(root: Path) -> None:
    for rel_path in MEMORY_DIRS:
        (root / rel_path).mkdir(parents=True, exist_ok=True)


def read_file_source(root: Path, input_file: str, source_id: str | None) -> IngestSource:
    input_path = ensure_within_root(root, root / input_file)
    if not input_path.exists():
        raise SystemExit(f"Input file does not exist: {input_file}")
    if input_path.suffix.lower() not in ALLOWED_INPUT_SUFFIXES:
        allowed = ", ".join(sorted(ALLOWED_INPUT_SUFFIXES))
        raise SystemExit(f"Input file must be markdown or text ({allowed}): {input_file}")
    content = input_path.read_text(encoding="utf-8")
    title = input_path.stem.replace("-", " ").replace("_", " ").strip() or "Factory memory input"
    return IngestSource(
        source_type="file",
        source_id=source_id or input_path.stem,
        title=title,
        content=content,
        original_path=str(input_path.relative_to(root.resolve())),
    )


def read_issue_source(issue_number: str, issue_title: str | None, issue_body_file: str | None) -> IngestSource:
    body = ""
    if issue_body_file:
        body_path = Path(issue_body_file)
        if body_path.exists():
            body = body_path.read_text(encoding="utf-8")
    title = issue_title or f"Issue {issue_number}"
    content = f"# {title}\n\nSource issue: #{issue_number}\n\n{body.strip()}\n"
    return IngestSource(source_type="issue", source_id=f"issue-{issue_number}", title=title, content=content)


def write_markdown(path: Path, content: str, dry_run: bool) -> None:
    if dry_run:
        print(f"DRY-RUN would write {path}")
        return
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")


def build_outputs(root: Path, source: IngestSource, dry_run: bool) -> dict[str, str]:
    if not dry_run:
        ensure_memory_dirs(root)
    stamp = utc_stamp()
    base_slug = slugify(f"{source.source_id}-{source.title}")
    source_name = f"{stamp}-{base_slug}.md"

    inbox_path = root / "factory-memory" / "chats" / "inbox" / source_name
    summary_path = root / "factory-memory" / "chats" / "summaries" / f"{stamp}-{base_slug}-summary.md"
    decision_path = root / "factory-memory" / "decisions" / f"{stamp}-{base_slug}-decision.md"
    lesson_path = root / "factory-memory" / "lessons-learned" / f"{stamp}-{base_slug}-lesson.md"
    skill_path = root / "factory-memory" / "skills" / f"{stamp}-{base_slug}-skill-update.md"

    source_header = [
        "# Factory Memory Source",
        "",
        f"- Source type: {source.source_type}",
        f"- Source ID: {source.source_id}",
        f"- Title: {source.title}",
        f"- Ingested at: {stamp}",
    ]
    if source.original_path:
        source_header.append(f"- Original path: {source.original_path}")
    source_header.extend(["", "## Source content", "", source.content.strip(), ""])

    summary = f"""# Factory Memory Summary Stub

- Source ID: {source.source_id}
- Source title: {source.title}
- Ingested at: {stamp}
- Status: stub

## Deterministic summary

Summary not generated by an LLM in AUTO-003 v1. Human or approved LLM station must replace this stub through a reviewed PR.

## Evidence to review

- Source file: `{inbox_path.relative_to(root)}`

## Required reviewer action

- Confirm scope.
- Extract accepted decisions.
- Extract accepted lessons learned.
- Approve, revise, or reject skill-update recommendations.
"""

    decision = f"""# Decision Record Stub

- Source ID: {source.source_id}
- Source title: {source.title}
- Ingested at: {stamp}
- Status: proposed stub

## Decision

Pending human extraction.

## Rationale

Pending review of `{inbox_path.relative_to(root)}`.

## Authority

Human approval required before this becomes factory guidance.
"""

    lesson = f"""# Lesson Learned Stub

- Source ID: {source.source_id}
- Source title: {source.title}
- Ingested at: {stamp}
- Status: proposed stub

## Lesson

Pending human extraction.

## Trigger or failure mode

Pending review of `{inbox_path.relative_to(root)}`.

## Verification method

Pending review.
"""

    skill = f"""# Skill Update Recommendation Stub

- Source ID: {source.source_id}
- Source title: {source.title}
- Ingested at: {stamp}
- Status: proposed stub

## Candidate skill or plugin

Pending classification.

## Recommended update

Pending human or approved LLM review.

## Acceptance condition

No skill, agent, or plugin update is accepted until a reviewed PR updates the relevant controlled pack.
"""

    write_markdown(inbox_path, "\n".join(source_header), dry_run)
    write_markdown(summary_path, summary, dry_run)
    write_markdown(decision_path, decision, dry_run)
    write_markdown(lesson_path, lesson, dry_run)
    write_markdown(skill_path, skill, dry_run)

    outputs = {
        "source": str(inbox_path.relative_to(root)),
        "summary": str(summary_path.relative_to(root)),
        "decision": str(decision_path.relative_to(root)),
        "lesson": str(lesson_path.relative_to(root)),
        "skill_update": str(skill_path.relative_to(root)),
    }
    return outputs


def main() -> int:
    parser = argparse.ArgumentParser(description="Ingest chat or issue evidence into factory-memory")
    parser.add_argument("--root", default=".", help="Repository root")
    source_group = parser.add_mutually_exclusive_group(required=True)
    source_group.add_argument("--input-file", help="Markdown/text source path inside the repository")
    source_group.add_argument("--issue-number", help="GitHub issue number used as source")
    parser.add_argument("--issue-title", help="Issue title when --issue-number is used")
    parser.add_argument("--issue-body-file", help="Issue body file when --issue-number is used")
    parser.add_argument("--source-id", help="Optional stable source ID for file ingests")
    parser.add_argument("--output-json", help="Optional path for JSON output metadata")
    parser.add_argument("--dry-run", action="store_true", help="Print planned writes without writing files")
    args = parser.parse_args()

    root = Path(args.root).resolve()
    if not root.exists():
        raise SystemExit(f"Root does not exist: {root}")

    if args.input_file:
        source = read_file_source(root, args.input_file, args.source_id)
    else:
        source = read_issue_source(args.issue_number, args.issue_title, args.issue_body_file)

    outputs = build_outputs(root, source, args.dry_run)
    result = {
        "status": "dry-run" if args.dry_run else "created",
        "source_type": source.source_type,
        "source_id": source.source_id,
        "title": source.title,
        "outputs": outputs,
    }

    rendered = json.dumps(result, indent=2, sort_keys=True)
    print(rendered)
    if args.output_json and not args.dry_run:
        Path(args.output_json).write_text(rendered + "\n", encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
